[project]
name = "storage-performance-monitor"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
    "aiofiles>=24.1.0",
    "aiosqlite>=0.21.0",
    "fastapi[standard]>=0.116.1",
    "psutil>=7.0.0",
    "sqlmodel>=0.0.24",
    "uvicorn>=0.35.0",
]
